version: '3.8'
services:
  nextjs:
    image: node:20.11.1-alpine
    container_name: nextjs
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    depends_on:
      - nextjs
