import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

import { Roboto } from 'next/font/google';
import Header from '@/components/header/header';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` overflow-x-hidden ${roboto.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header></Header>
          <div className="lg:px-16   pt-20 overflow-x-hidden max-lg:px-3  max-lg:pt-[136px]">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
