export const env = {
  NEXT_PUBLIC_PORT_NEST_SERVER: () => process.env.NEXT_PUBLIC_PORT_NEST_SERVER,
  NEXT_PUBLIC_PORT_SOCKET_SERVER: () => process.env.NEXT_PUBLIC_PORT_SOCKET_SERVER,
  NEXT_PUBLIC_KEY_GHN_DEV: () => process.env.NEXT_PUBLIC_KEY_GHN_DEV,
};
